trigger: none 

pool:
  vmImage: ubuntu-latest

parameters:
  - name: Module
    displayName: 'Select the test'
    type: string
    default: loginTest.spec.ts
    values:
      - loginTest.spec.ts
      - pimTest.spec.ts
      - adminTest.spec.ts

  - name: Browser
    displayName: 'Select the browser'
    type: string
    default: chrome
    values:
      - chrome
      - firefox
      - safari

steps:
  - script: echo "Running the test ${{ parameters.Module }} on ${{ parameters.Browser }}"
    displayName: 'Selected test run with selected browser'

  - script: |
      npx playwright install
      npx playwright test tests/${{ parameters.Module }} --project=${{ parameters.Browser }}
    displayName: 'Run the Playwright test'
