trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl -X POST "https://3943-183-82-115-164.ngrok-free.app/job/Jenkins_With_ADO/buildWithParameters?Module=loginTest.spec.ts&Browser=chromium&token=triggerado&cause=Triggered+from+ADO" \
    --user "vamsi:11a575a43f6719cd829522c842d633500f"
  displayName: "Trigger Jenkins Job from ADO"
