trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: Module
    displayName: "Select Test"
    type: string
    default: "loginTest.spec.ts"
    values:
      - "loginTest.spec.ts"
      - "pimTest.spec.ts"

steps:
- script: |
    echo "Triggering Jenkins with selected module: $(Module)"
    curl -v -X POST "https://7fbd-183-82-115-164.ngrok-free.app/job/Fresh_Jenkins_NodeWay_Trigger/buildWithParameters?MODULE=$(Module)&token=triggerado" \
    --user "ado:115ea4a5694c83bc35b4e9ac4bb8ac19a8"
  displayName: "Trigger Jenkins Pipeline"
