const infoLocs = {
  myInfo: "//span[text()='My Info']",
  personalDetails: '//a[text()="Personal Details"]',
  firstName: "//input[@name='firstName']",
  middleName: 'input[name=middleName]',
  lastName: 'input[name=lastName]',
  employeeId: '//label[text()="Employee Id"]/../../div/input',
  otherId: '//label[text()="Other Id"]/../../div/input',
  drivingLicenseNum: '//label[text()="Driver\'s License Number"]/../../div/input',
  licenseData: '//label[text()="License Expiry Date"]/following::input[1]',
  nationality: "(//div[contains(@class, 'oxd-select-text-input')])[1]",
  dob: '//label[text()="Date of Birth"]/following::input[1]',
  maritalStatus: "(//div[contains(@class, 'oxd-select-text-input')])[2]",
  maleCheckbox: "//label[normalize-space()='Male']",
  femaleCheckbox: "//label[normalize-space()='FeMale']",
  saveBtn: "button[type='submit']",
  successPopupMessage: "//p[contains(@class, 'oxd-text--toast-title')]",
  contactDetails: "//a[text()='Contact Details']",
  street1: '//label[text()="Street 1"]/../../div/input',
  street2: '//label[text()="Street 2"]/../../div/input',
  city: '//label[text()="City"]/../../div/input',
  state: '//label[text()="State/Province"]/../../div/input',
  postalCode: '//label[text()="Zip/Postal Code"]/../../div/input',
  home: '//label[text()="Home"]/../../div/input',
  mobile: '//label[text()="Mobile"]/../../div/input',
  work: '//label[text()="Work"]/../../div/input',
  workEmail: '//label[text()="Work Email"]/../../div/input',
  otherEmail: '//label[text()="Other Email"]/../../div/input',
  country: "//div[@class='oxd-select-text-input']",
  verifyPersonalDetails: ".oxd-userdropdown-name",
  emergencyContacts: "//a[text()='Emergency Contacts']",
  addContactBtn: "//h6[text()='Assigned Emergency Contacts']/../../div/button",
  name: '//label[text()="Name"]/../../div/input',
  relationship: '//label[text()="Relationship"]/../../div/input',
  homeTelephone: '//label[text()="Home Telephone"]/../../div/input',
  workTelephone: '//label[text()="Work Telephone"]/../../div/input',
  mobileNumber: '//label[text()="Mobile"]/../../div/input',
  dependents: "//a[text()='Dependents']",
  addDependentsbtn: "//h6[text()='Assigned Dependents']/../../div/button",
  relation: "(//div[contains(@class, 'oxd-select-text-input')])[1]",
  other: "//span[text()='Other']",
  specifyRelation: '//label[text()="Please Specify"]/../../div/input'
};

export default infoLocs;

